apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cpu-small.yaml
  - cpu-medium.yaml
  - cpu-large.yaml
  - gpu-t4.yaml

# Add new runners here as you create them
# - your-new-runner.yaml
